import{r as c,j as i}from"../assets/jsx-runtime.js";import{u as j}from"../contexts/WindowContext.js";import{A as z}from"../assets/index.js";import{m as k}from"../assets/proxy.js";import{c as r}from"../assets/createLucideIcon.js";import{X as N}from"../assets/x.js";/**
 * @license lucide-react v0.522.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const W=[["rect",{width:"14",height:"14",x:"8",y:"8",rx:"2",ry:"2",key:"17jyea"}],["path",{d:"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2",key:"zix9uf"}]],L=r("copy",W);/**
 * @license lucide-react v0.522.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const _=[["path",{d:"M5 12h14",key:"1ays0h"}]],E=r("minus",_);/**
 * @license lucide-react v0.522.0 - ISC
 *
 * This source code is licensed under the ISC license.
 * See the LICENSE file in the root directory of this source tree.
 */const P=[["rect",{width:"18",height:"18",x:"3",y:"3",rx:"2",key:"afitv7"}]],w=r("square",P),H=({windowData:e})=>{const{closeWindow:h,minimizeWindow:x,maximizeWindow:a,focusWindow:u,activeWindowId:p}=j(),f=p===e.id;c.useRef(null);const[s,g]=c.useState(e.defaultSize||{width:600,height:400}),[o,v]=c.useState({x:typeof window<"u"?(window.innerWidth-s.width)/2+(Math.random()*40-20):100,y:typeof window<"u"?(window.innerHeight-s.height)/2+(Math.random()*40-20):100});return e.isOpen?i.jsx(z,{children:!e.isMinimized&&i.jsxs(k.div,{drag:!e.isMaximized,dragMomentum:!1,dragHandle:".title-bar",initial:{scale:.8,opacity:0},animate:{scale:1,opacity:1,x:e.isMaximized?0:o.x,y:e.isMaximized?0:o.y,width:e.isMaximized?"100vw":s.width,height:e.isMaximized?"calc(100vh - 40px)":s.height},exit:{scale:.8,opacity:0,y:"100vh"},transition:{type:"spring",damping:25,stiffness:300},onDragEnd:(t,n)=>{v({x:o.x+n.offset.x,y:o.y+n.offset.y})},onMouseDown:()=>u(e.id),style:{zIndex:e.zIndex},className:`absolute flex flex-col win-bg win-border shadow-[2px_2px_10px_rgba(0,0,0,0.5)] ${e.isMaximized?"top-0 left-0":""}`,children:[i.jsxs("div",{className:`title-bar flex items-center justify-between px-1 py-1 cursor-default ${f?"titlebar-active":"titlebar-inactive"}`,onDoubleClick:()=>a(e.id),children:[i.jsxs("div",{className:"flex items-center gap-2 overflow-hidden",children:[i.jsx("div",{className:"w-4 h-4 flex-shrink-0",children:e.icon}),i.jsx("span",{className:"font-pixel text-sm truncate tracking-wider mt-0.5",children:e.title})]}),i.jsxs("div",{className:"flex gap-0.5 flex-shrink-0 ml-2",children:[i.jsx("button",{className:"win-button w-5 h-5",onClick:t=>{t.stopPropagation(),x(e.id)},children:i.jsx(E,{size:12,className:"text-black",strokeWidth:3})}),i.jsx("button",{className:"win-button w-5 h-5",onClick:t=>{t.stopPropagation(),a(e.id)},children:e.isMaximized?i.jsx(L,{size:10,className:"text-black",strokeWidth:3}):i.jsx(w,{size:10,className:"text-black",strokeWidth:3})}),i.jsx("button",{className:"win-button w-5 h-5 ml-1",onClick:t=>{t.stopPropagation(),h(e.id)},children:i.jsx(N,{size:14,className:"text-black",strokeWidth:3})})]})]}),i.jsx("div",{className:"flex-1 overflow-auto bg-white win-border-inset m-1 relative",children:e.content}),!e.isMaximized&&i.jsx("div",{className:"absolute bottom-0 right-0 w-4 h-4 cursor-se-resize",onMouseDown:t=>{t.preventDefault(),t.stopPropagation();const n=t.clientX,y=t.clientY,b=s.width,M=s.height,l=m=>{g({width:Math.max(200,b+m.clientX-n),height:Math.max(150,M+m.clientY-y)})},d=()=>{document.removeEventListener("mousemove",l),document.removeEventListener("mouseup",d)};document.addEventListener("mousemove",l),document.addEventListener("mouseup",d)},children:i.jsx("svg",{viewBox:"0 0 10 10",className:"w-full h-full opacity-50",children:i.jsx("path",{d:"M 8 10 L 10 8 L 10 10 Z M 5 10 L 10 5 L 10 7 L 7 10 Z M 2 10 L 10 2 L 10 4 L 4 10 Z",fill:"black"})})})]})}):null};export{H as W};
